tareas:
    path: /tareas
    controller: App\Controller\TareaController::index

registro:
    path: /registro
    controller: App\Controller\UsuarioController::registro

login:
    path: /login
    controller: App\Controller\UsuarioController::login

logout:
    path: /logout

